### ISSUE TITLE
Entry light

### ISSUE THREAD

**Issue by brandievo** [BarrettLowe/HomeAssistantConfig#15]
Automation
If someone is home
AND if between hours of 7am and 7pm (even better could be sunrise to sunset) then entry light should be on

Curious what you think of this idea!

**Comment by BarrettLowe** [comment]
Do you still want this?

**Comment by BarrettLowe** [comment]
Instead I'll add Entry to living room group

**Comment by BarrettLowe** [comment]
fixed in 9adea5
