### ISSUE TITLE
Alert to close sliding door

### ISSUE THREAD

**Issue by brandievo** [BarrettLowe/HomeAssistantConfig#18]
Goal is to let us know that we should close slider if it's warmer outside than inside/so we don't air condition Texas

Sliding door open/close sensor - if open more than 90 seconds maybe
Could be done for if if temp outside > temp inside OR if a/c is actively running (not fan) based on energy monitor
Could incorporate if it's free energy time or not

**Comment by BarrettLowe** [comment]
closed in 235d41f
