### ISSUE TITLE
Smart Button for Nursery

### ISSUE THREAD

**Issue by brandievo** [BarrettLowe/HomeAssistantConfig#19]
1. Nursery brighten the room (script already exists)
2. Nursery dark (hallway lights off + only the futon light at 1, other lights in nursery are off)
3. Summon Barrett: figure out how this works in all the different contexts
4. Start white noise--assuming we one day have a speaker/snapcast system in the room
5. All Lights off in 60 seconds (same as we use going to bed, but delayed for me to walk to bed)
6. 
7. 
8.

**Comment by BarrettLowe** [comment]
Done
